[general]
live_config_reload = true
ipc_socket = false
import = [
    "local.toml"
]

[font]
normal = { family = "Fira Mono", style = "Regular" }
size = 14

[bell]
duration = 0

[keyboard]
bindings = [
    { key = "Insert", mods = "Shift", action = "Paste" }
]

[terminal]
osc52 = "OnlyCopy"
